#!/bin/bash

curcommit=$(git rev-parse --abbrev-ref HEAD)
prevcommit=$(git rev-parse $2)

oldfilename="${RANDOM}.tex"
newfilename="${RANDOM}.tex"

git checkout $prevcommit

quarto render $1 --to latex --output ${oldfilename}

git checkout $curcommit

quarto render $1 --to latex --output ${newfilename}

latexdiff --flatten ${oldfilename} ${newfilename} > diff.tex

latexmk -pdf diff.tex && latexmk -c diff.tex

rm diff.tex ${oldfilename} ${newfilename}